### ISSUE TITLE
Problem with $ dollar sign

### ISSUE THREAD

**Issue by jonaprieto** [banacorn/language-agda#11]
A pic for this:

![image](https://user-images.githubusercontent.com/1428088/42328484-a2bb8dc2-806e-11e8-8e86-2999737260d2.png)

**Comment by banacorn** [comment]
I will tag this as "won't fix". And I'm considering closing this issue after literate Agda is available with the new [tree-sitter parser](https://github.com/tree-sitter/tree-sitter-agda) for syntax highlighting

**Comment by jonaprieto** [comment]
Oh, yes. Good.
