### ISSUE TITLE
Many keywords do not highlight as such

### ISSUE THREAD

**Issue by exists-forall** [banacorn/language-agda#5]
Most importantly, the syntax highlighting grammar in this package does not identify `let`, `in`, or `with` as keywords, making it more difficult to read code that uses these constructs.

More generally, not all keywords [from this list of keywords](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=ReferenceManual.Keywords) seem to highlight:

```
 =
 |
 ->
 :
 ?
 \
 →
 ∀
 λ
 abstract
 constructor
 data
 field
 forall
 hiding
 import
 in
 infix
 infixl
 infixr
 let
 module
 mutual
 open
 postulate
 primitive
 Prop
 private
 public
 quoteGoal
 quoteTerm
 quote
 record
 renaming
 rewrite
 Set[0-9]*
 syntax
 unquote
 using
 where
 with
```

Highlighting may be inappropriate for the non-alphanumeric "keywords" like `→` and `∀`

**Comment by banacorn** [comment]
Thanks for listing the keywords out! 
The syntax highlighting is really lacking, but I have little knowledge about how Atom's language grammar works.

I guess I can only leave this issue open for the moment :(

**Comment by banacorn** [comment]
please try out the new parser! :)
