### ISSUE TITLE
tree-sitter-agda build error

### ISSUE THREAD

**Issue by zraffer** [banacorn/language-agda#8]
> tree-sitter-agda@1.0.4 install /tmp/apm-install-dir-118512-10784-1xgowtg.0030x80k9/node_modules/language-agda/node_modules/tree-sitter-agda
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-118512-10784-1xgowtg.0030x80k9/node_modules/language-agda/node_modules/tree-sitter-agda/build'
  CC(target) Release/obj.target/tree_sitter_agda_binding/src/parser.o
  CXX(target) Release/obj.target/tree_sitter_agda_binding/src/binding.o
  CXX(target) Release/obj.target/tree_sitter_agda_binding/src/scanner.o
tree_sitter_agda_binding.target.mk:101: recipe for target 'Release/obj.target/tree_sitter_agda_binding/src/scanner.o' failed
make: Leaving directory '/tmp/apm-install-dir-118512-10784-1xgowtg.0030x80k9/node_modules/language-agda/node_modules/tree-sitter-agda/build'

../src/scanner.cc: In member function ‘void {anonymous}::Scanner::printValidSymbols(const bool*)’:
../src/scanner.cc:53:17: error: ‘printf’ was not declared in this scope
                 printf("<dedent> ");
                 ^~~~~~
../src/scanner.cc:53:17: note: suggested alternative: ‘uint’
                 printf("<dedent> ");
                 ^~~~~~
                 uint
../src/scanner.cc:56:17: error: ‘printf’ was not declared in this scope
                 printf("<indent> ");
                 ^~~~~~
../src/scanner.cc:56:17: note: suggested alternative: ‘uint’
                 printf("<indent> ");
                 ^~~~~~
                 uint
../src/scanner.cc:59:17: error: ‘printf’ was not declared in this scope
                 printf("<newline> ");
                 ^~~~~~
../src/scanner.cc:59:17: note: suggested alternative: ‘uint’
                 printf("<newline> ");
                 ^~~~~~
                 uint
../src/scanner.cc:61:13: error: ‘printf’ was not declared in this scope
             printf("\n");
             ^~~~~~
../src/scanner.cc:61:13: note: suggested alternative: ‘uint’
             printf("\n");
             ^~~~~~
             uint
make: *** [Release/obj.target/tree_sitter_agda_binding/src/scanner.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom-beta/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.17.1-041701-generic
gyp ERR! command "/usr/share/atom-beta/resources/app/apm/bin/node" "/usr/share/atom-beta/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118512-10784-1xgowtg.0030x80k9/node_modules/language-agda/node_modules/tree-sitter-agda
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118512-10784-1xgowtg.0030x80k9/package.json'
npm WARN apm-install-dir-118512-10784-1xgowtg.0030x80k9 No description
npm WARN apm-install-dir-118512-10784-1xgowtg.0030x80k9 No repository field.
npm WARN apm-install-dir-118512-10784-1xgowtg.0030x80k9 No README data
npm WARN apm-install-dir-118512-10784-1xgowtg.0030x80k9 No license field.
npm ERR! Linux 4.17.1-041701-generic
npm ERR! argv "/usr/share/atom-beta/resources/app/apm/bin/node" "/usr/share/atom-beta/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/me/.atom/.apm/.apmrc" "--userconfig" "/home/me/.atom/.apmrc" "install" "/tmp/d-118512-10784-1sva741.ifxui0be29/package.tgz" "--runtime=electron" "--target=2.0.1" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tree-sitter-agda@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-agda@1.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tree-sitter-agda package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tree-sitter-agda
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tree-sitter-agda
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118512-10784-1xgowtg.0030x80k9/npm-debug.log

**Comment by banacorn** [comment]
This looks nasty, I'll see what I can do!

**Comment by banacorn** [comment]
Oops, sorry I closed this issue by mistake (cross-repository issue reference)

It seems like the problem arose from my bad C code in the scanner.
I've removed the rotten part and the patch should be on the way!

**Comment by banacorn** [comment]
The issue got closed by GitHub again XD.
But I'm leaving it closed this time, as the issue should've been gone.
Feel free to reopen this issue if there's still any problem!

**Comment by zraffer** [comment]
It installs and works well now. Thank you very much.

**Comment by zraffer** [comment]
Now it makes color syntax with default settings. But when I check "Use Tree Sitter" in the Setting-Core, I see no color. It is an experimental option, I see.

**Comment by banacorn** [comment]
Interesting, because your code should be **a lot more colourful** if you opt-in *Use Tree Sitter Parsers*

**Comment by zraffer** [comment]
I'm testing the package on Atom-1.28.0-beta3. May be Tree Sitter API have changed?

**Comment by banacorn** [comment]
That's quite possible!

**Comment by zraffer** [comment]
I've installed Atom-1.27.2 and reinstalled language-agda, but still no colors while Tree Sitter enabled. 
I'm using Agda-2.5.4 (being built by `cabal install Agda`) at Ubuntu 18.04, if it can help.

**Comment by banacorn** [comment]
I suspect that there are some Node version compatibility problem. 

To see if that's true, please open `View > Developer > Toggle Developer Tool` and see if there's any error message in the console.

**Comment by zraffer** [comment]
No messages in the console tab, even after reinstall. Sorry.

**Comment by zraffer** [comment]
Whoa! It was `{-# OPTIONS ... #-}` at the first line who broke parsing! Now I see all colors.

By the way, what syntax color scheme did you use when screenshoting?

**Comment by banacorn** [comment]
Okay, now I have to fix that pragma XD

The syntax scheme is *One Dark*
