### ISSUE TITLE
the new grammar needs fix

### ISSUE THREAD

**Issue by zraffer** [banacorn/language-agda#9]
Now it compiles and works, but I see a few bug in parsing, so I consider this as a distinct issue.

1. `{-# OPTIONS --type-in-type #-}` makes all the text below to be comment

2. unicode identifiers breaks parsing:
```
  𝕆 : ∅
  𝕆 = ∅
```
changes all coloring after them.

**Comment by banacorn** [comment]
Thanks! I'll look into this in the morning (GMT+8)

By the way, Atom's syntax highlighting is still a bit buggy, sometimes it might apply the wrong color even if it was parsed correctly, and if that's the case then all we can do is wait 😅

**Comment by banacorn** [comment]
1. `{-# OPTIONS --type-in-type #-}` problem reproduced and fixed in the latest patch
2. unicode identifiers should be cool, "jiggle" the code around may fix it, Atom's acting wierd
